name: CI/CD for C++ Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu_latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.21.2'

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_TESTING=ON

      - name: Build
        run: |
          cd build
          make

      - name: Chore
        run: mkdir data

      - name: Run tests
        working-directory: ./data
        run: |
          cd build
          ctest --output-on-failure
